# Custom properties to ease configuration overrides
# on command-line or IDE launch configurations

#**********************************************************************************************************************#
#***************************************************** VARIABLES ******************************************************#
#**********************************************************************************************************************#

# server settings
dse-servers.scheme: http
dse-servers.hostname: localhost

# reverse proxy server
dse-servers.reverse-proxy-port: 7080

# bff server
dse-servers.bff-prefix: /bff

# authorization server
dse-servers.authorization-server-port: 6060
dse-servers.authorization-server-prefix: /auth
dse-servers.in-house-auth-registration-id: in-house-auth-server

#**********************************************************************************************************************#
#************************************************** SPRING SETTINGS ***************************************************#
#**********************************************************************************************************************#

# spring settings
spring:
  # profile settings
  profiles:
    active: ssl
  # session redis configurations
  session:
    redis:
      namespace: spring:session:in-house-auth-server
      repository-type: indexed
      flush-mode: on-save
    timeout: 30

#**********************************************************************************************************************#
#************************************************** SERVER SETTINGS ***************************************************#
#**********************************************************************************************************************#

# current server settings
server:
  port: ${dse-servers.authorization-server-port}
  ssl:
    enabled: false

#**********************************************************************************************************************#
#************************************************* PROFILE SETTINGS ***************************************************#
#**********************************************************************************************************************#

# spring profile settings
---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    # This has been disabled!
    enabled: false

#**********************************************************************************************************************#
#*********************************************** MANAGEMENT SETTINGS **************************************************#
#**********************************************************************************************************************#

# endpoint settings
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

#**********************************************************************************************************************#
#************************************************ LOGGING SETTINGS ****************************************************#
#**********************************************************************************************************************#

# logging configurations
logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO
        security: TRACE
        web: INFO

#**********************************************************************************************************************#
#************************************************** END OF YAML *******************************************************#
#**********************************************************************************************************************#