# Custom properties to ease configuration overrides
# on command-line or IDE launch configurations

# server settings
scheme: http
hostname: localhost

# reverse proxy
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}

# bff server
bff-prefix: /bff

# authorization server
authorization-server-port: 6060
authorization-server-prefix: /auth
in-house-auth-registration-id: in-house-auth-server
in-house-issuer-uri: ${reverse-proxy-uri}${authorization-server-prefix}

# spring settings
spring:
  # profile settings
  profiles:
    active: ssl

# current server settings
server:
  port: ${authorization-server-port}
  ssl:
    enabled: false
  servlet:
    session:
      cookie:
        name: AUTH-SESSIONID
        path: /
        max-age: 5s
        secure: false # scope is not just on secure connections
        http-only: true
        same-site: STRICT
      timeout=5s:

# endpoint settings
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# logging configurations
logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO
        security: TRACE
        web: INFO

# spring profile settings
---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    # this has been disabled!
    enabled: false
    # this has been disabled!
scheme: http