# Custom properties to ease configuration overrides
# on command-line or IDE launch configurations

#**********************************************************************************************************************#
#***************************************************** VARIABLES ******************************************************#
#**********************************************************************************************************************#

# server settings
scheme: http
hostname: localhost

# reverse proxy
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}

# bff server
bff-prefix: /bff

# authorization server
authorization-server-port: 6060
authorization-server-prefix: /auth
in-house-auth-registration-id: in-house-auth-server
in-house-issuer-uri: ${reverse-proxy-uri}${authorization-server-prefix}

#**********************************************************************************************************************#
#************************************************** SPRING SETTINGS ***************************************************#
#**********************************************************************************************************************#

# spring settings
spring:
  # profile settings
  profiles:
    active: ssl
  # session redis configurations
  session:
    redis:
      namespace: spring:session:in-house-auth-server
      repository-type: indexed
      flush-mode: on-save
    timeout: 30

#**********************************************************************************************************************#
#************************************************** SERVER SETTINGS ***************************************************#
#**********************************************************************************************************************#

# current server settings
server:
  port: ${authorization-server-port}
  ssl:
    enabled: false

#**********************************************************************************************************************#
#************************************************** SPRING SETTINGS ***************************************************#
#**********************************************************************************************************************#

security:
  remember-me:
    key: S/MqST4}8Weo)OLyL$N|9RY-.|.46zpVtb'{wVf~IdgWk#r>D[9DzUCL|DTv_Hb

#**********************************************************************************************************************#
#************************************************* PROFILE SETTINGS ***************************************************#
#**********************************************************************************************************************#

# spring profile settings
---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    # This has been disabled!
    enabled: false

#**********************************************************************************************************************#
#*********************************************** MANAGEMENT SETTINGS **************************************************#
#**********************************************************************************************************************#

# endpoint settings
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

#**********************************************************************************************************************#
#************************************************ LOGGING SETTINGS ****************************************************#
#**********************************************************************************************************************#

# logging configurations
logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO
        security: TRACE
        web: INFO

#**********************************************************************************************************************#
#************************************************** END OF YAML *******************************************************#
#**********************************************************************************************************************#