#**********************************************************************************************************************#
#************************************************* PROFILE SETTINGS ***************************************************#
#**********************************************************************************************************************#

# spring profile settings
---
spring:
  config:
    activate:
      on-profile: dev
server:
  ssl:
    enabled: false
  reactive:
    session:
      timeout: ${TIMEOUT_SESSION}

#**********************************************************************************************************************#
#************************************************** END OF YAML *******************************************************#
#**********************************************************************************************************************#